enum ActionTypes {
  REQUEST_GET_UPBIT_DWM_CANDLE = 'REQUEST_GET_UPBIT_DWM_CANDLE',
  REQUEST_GET_UPBIT_DWM_CANDLE_SUCCESS = 'REQUEST_GET_UPBIT_DWM_CANDLE_SUCCESS',
  REQUEST_GET_UPBIT_DWM_CANDLE_ERROR = 'REQUEST_GET_UPBIT_DWM_CANDLE_ERROR',

  REQUEST_GET_UPBIT_MINUTE_CANDLE = 'REQUEST_GET_UPBIT_MINUTE_CANDLE',
  REQUEST_GET_UPBIT_MINUTE_CANDLE_SUCCESS = 'REQUEST_GET_UPBIT_MINUTE_CANDLE_SUCCESS',
  REQUEST_GET_UPBIT_MINUTE_CANDLE_ERROR = 'REQUEST_GET_UPBIT_MINUTE_CANDLE_ERROR',

  /* Web Socket Actions */
  CONNECT_WEB_SOCKET = 'CONNECT_WEB_SOCKET',
  DISCONNECT_WEB_SOCKET = 'DISCONNECT_WEB_SOCKET',

  RECEIVED_TICKER_DATA = 'RECEIVED_TICKER_DATA',
}

export default ActionTypes
