enum ActionTypes {
  REQUEST_GET_UPBIT_DWM_CANDLE = 'REQUEST_GET_UPBIT_DWM_CANDLE',
  REQUEST_GET_UPBIT_DWM_CANDLE_SUCCESS = 'REQUEST_GET_UPBIT_DWM_CANDLE_SUCCESS',
  REQUEST_GET_UPBIT_DWM_CANDLE_ERROR = 'REQUEST_GET_UPBIT_DWM_CANDLE_ERROR',

  REQUEST_GET_UPBIT_MINUTE_CANDLE = 'REQUEST_GET_UPBIT_MINUTE_CANDLE',
  REQUEST_GET_UPBIT_MINUTE_CANDLE_SUCCESS = 'REQUEST_GET_UPBIT_MINUTE_CANDLE_SUCCESS',
  REQUEST_GET_UPBIT_MINUTE_CANDLE_ERROR = 'REQUEST_GET_UPBIT_MINUTE_CANDLE_ERROR',
}

export default ActionTypes
